import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import styles from "@/styles/style.module.scss"
import Header from "@/components/Header"
import Timeline from "@/components/Timeline";
import Post from "@/components/Post";
import { mockData } from "@/mock/data";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Header /> 
        <Timeline />
        <div>
          {mockData && mockData.map((item, index)=>(
            <Post 
              key={index}
              name={item.name}
              date={item.date}
              content={item.content}
              link={item.link}
            />
            ))}
        </div>
      </main>
    </>
  );
}
